#include <tap.h>
#include "./../src/arithmetic/mod.h"


void CRUX__mod_iu08_tests (void) {
  const IU08 max = IU08_MAX;
  const IU08 min = IU08_MIN;
  const IU08 nil = as_iu08(0);
  const IU08 one = as_iu08(1);
  CRUX__ResultIU08 max_max = CRUX__mod(max, max);
  CRUX__ResultIU08 max_min = CRUX__mod(max, min);
  CRUX__ResultIU08 max_nil = CRUX__mod(max, nil);
  CRUX__ResultIU08 max_one = CRUX__mod(max, one);
  CRUX__ResultIU08 min_max = CRUX__mod(min, max);
  CRUX__ResultIU08 min_min = CRUX__mod(min, min);
  CRUX__ResultIU08 min_nil = CRUX__mod(min, nil);
  CRUX__ResultIU08 min_one = CRUX__mod(min, one);
  CRUX__ResultIU08 nil_max = CRUX__mod(nil, max);
  CRUX__ResultIU08 nil_min = CRUX__mod(nil, min);
  CRUX__ResultIU08 nil_nil = CRUX__mod(nil, nil);
  CRUX__ResultIU08 nil_one = CRUX__mod(nil, one);
  CRUX__ResultIU08 one_max = CRUX__mod(one, max);
  CRUX__ResultIU08 one_min = CRUX__mod(one, min);
  CRUX__ResultIU08 one_nil = CRUX__mod(one, nil);
  CRUX__ResultIU08 one_one = CRUX__mod(one, one);
  ok(CRUX__trace_check(max_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(max_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(max_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(max_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(min_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(min_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(min_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(nil_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(nil_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(nil_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(one_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(one_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(one_one.trace), "Must not have an error.");
  ok(CRUX__is_equal(max_max.value, nil), "Must be equal to %"IU08_FMT".", nil);
  ok(CRUX__is_equal(max_one.value, nil), "Must be equal to %"IU08_FMT".", nil);
  ok(CRUX__is_equal(min_max.value, nil), "Must be equal to %"IU08_FMT".", nil);
  ok(CRUX__is_equal(min_one.value, nil), "Must be equal to %"IU08_FMT".", nil);
  ok(CRUX__is_equal(nil_max.value, nil), "Must be equal to %"IU08_FMT".", nil);
  ok(CRUX__is_equal(nil_one.value, nil), "Must be equal to %"IU08_FMT".", nil);
  ok(CRUX__is_equal(one_max.value, one), "Must be equal to %"IU08_FMT".", one);
  ok(CRUX__is_equal(one_one.value, nil), "Must be equal to %"IU08_FMT".", nil);
  CRUX__trace_clean(&max_max.trace);
  CRUX__trace_clean(&max_min.trace);
  CRUX__trace_clean(&max_nil.trace);
  CRUX__trace_clean(&max_one.trace);
  CRUX__trace_clean(&min_max.trace);
  CRUX__trace_clean(&min_min.trace);
  CRUX__trace_clean(&min_nil.trace);
  CRUX__trace_clean(&min_one.trace);
  CRUX__trace_clean(&nil_max.trace);
  CRUX__trace_clean(&nil_min.trace);
  CRUX__trace_clean(&nil_nil.trace);
  CRUX__trace_clean(&nil_one.trace);
  CRUX__trace_clean(&one_max.trace);
  CRUX__trace_clean(&one_min.trace);
  CRUX__trace_clean(&one_nil.trace);
  CRUX__trace_clean(&one_one.trace);
}


void CRUX__mod_iu16_tests (void) {
  const IU16 max = IU16_MAX;
  const IU16 min = IU16_MIN;
  const IU16 nil = as_iu16(0);
  const IU16 one = as_iu16(1);
  CRUX__ResultIU16 max_max = CRUX__mod(max, max);
  CRUX__ResultIU16 max_min = CRUX__mod(max, min);
  CRUX__ResultIU16 max_nil = CRUX__mod(max, nil);
  CRUX__ResultIU16 max_one = CRUX__mod(max, one);
  CRUX__ResultIU16 min_max = CRUX__mod(min, max);
  CRUX__ResultIU16 min_min = CRUX__mod(min, min);
  CRUX__ResultIU16 min_nil = CRUX__mod(min, nil);
  CRUX__ResultIU16 min_one = CRUX__mod(min, one);
  CRUX__ResultIU16 nil_max = CRUX__mod(nil, max);
  CRUX__ResultIU16 nil_min = CRUX__mod(nil, min);
  CRUX__ResultIU16 nil_nil = CRUX__mod(nil, nil);
  CRUX__ResultIU16 nil_one = CRUX__mod(nil, one);
  CRUX__ResultIU16 one_max = CRUX__mod(one, max);
  CRUX__ResultIU16 one_min = CRUX__mod(one, min);
  CRUX__ResultIU16 one_nil = CRUX__mod(one, nil);
  CRUX__ResultIU16 one_one = CRUX__mod(one, one);
  ok(CRUX__trace_check(max_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(max_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(max_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(max_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(min_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(min_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(min_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(nil_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(nil_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(nil_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(one_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(one_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(one_one.trace), "Must not have an error.");
  ok(CRUX__is_equal(max_max.value, nil), "Must be equal to %"IU16_FMT".", nil);
  ok(CRUX__is_equal(max_one.value, nil), "Must be equal to %"IU16_FMT".", nil);
  ok(CRUX__is_equal(min_max.value, nil), "Must be equal to %"IU16_FMT".", nil);
  ok(CRUX__is_equal(min_one.value, nil), "Must be equal to %"IU16_FMT".", nil);
  ok(CRUX__is_equal(nil_max.value, nil), "Must be equal to %"IU16_FMT".", nil);
  ok(CRUX__is_equal(nil_one.value, nil), "Must be equal to %"IU16_FMT".", nil);
  ok(CRUX__is_equal(one_max.value, one), "Must be equal to %"IU16_FMT".", one);
  ok(CRUX__is_equal(one_one.value, nil), "Must be equal to %"IU16_FMT".", nil);
  CRUX__trace_clean(&max_max.trace);
  CRUX__trace_clean(&max_min.trace);
  CRUX__trace_clean(&max_nil.trace);
  CRUX__trace_clean(&max_one.trace);
  CRUX__trace_clean(&min_max.trace);
  CRUX__trace_clean(&min_min.trace);
  CRUX__trace_clean(&min_nil.trace);
  CRUX__trace_clean(&min_one.trace);
  CRUX__trace_clean(&nil_max.trace);
  CRUX__trace_clean(&nil_min.trace);
  CRUX__trace_clean(&nil_nil.trace);
  CRUX__trace_clean(&nil_one.trace);
  CRUX__trace_clean(&one_max.trace);
  CRUX__trace_clean(&one_min.trace);
  CRUX__trace_clean(&one_nil.trace);
  CRUX__trace_clean(&one_one.trace);
}


void CRUX__mod_iu32_tests (void) {
  const IU32 max = IU32_MAX;
  const IU32 min = IU32_MIN;
  const IU32 nil = as_iu32(0);
  const IU32 one = as_iu32(1);
  CRUX__ResultIU32 max_max = CRUX__mod(max, max);
  CRUX__ResultIU32 max_min = CRUX__mod(max, min);
  CRUX__ResultIU32 max_nil = CRUX__mod(max, nil);
  CRUX__ResultIU32 max_one = CRUX__mod(max, one);
  CRUX__ResultIU32 min_max = CRUX__mod(min, max);
  CRUX__ResultIU32 min_min = CRUX__mod(min, min);
  CRUX__ResultIU32 min_nil = CRUX__mod(min, nil);
  CRUX__ResultIU32 min_one = CRUX__mod(min, one);
  CRUX__ResultIU32 nil_max = CRUX__mod(nil, max);
  CRUX__ResultIU32 nil_min = CRUX__mod(nil, min);
  CRUX__ResultIU32 nil_nil = CRUX__mod(nil, nil);
  CRUX__ResultIU32 nil_one = CRUX__mod(nil, one);
  CRUX__ResultIU32 one_max = CRUX__mod(one, max);
  CRUX__ResultIU32 one_min = CRUX__mod(one, min);
  CRUX__ResultIU32 one_nil = CRUX__mod(one, nil);
  CRUX__ResultIU32 one_one = CRUX__mod(one, one);
  ok(CRUX__trace_check(max_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(max_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(max_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(max_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(min_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(min_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(min_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(nil_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(nil_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(nil_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(one_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(one_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(one_one.trace), "Must not have an error.");
  ok(CRUX__is_equal(max_max.value, nil), "Must be equal to %"IU32_FMT".", nil);
  ok(CRUX__is_equal(max_one.value, nil), "Must be equal to %"IU32_FMT".", nil);
  ok(CRUX__is_equal(min_max.value, nil), "Must be equal to %"IU32_FMT".", nil);
  ok(CRUX__is_equal(min_one.value, nil), "Must be equal to %"IU32_FMT".", nil);
  ok(CRUX__is_equal(nil_max.value, nil), "Must be equal to %"IU32_FMT".", nil);
  ok(CRUX__is_equal(nil_one.value, nil), "Must be equal to %"IU32_FMT".", nil);
  ok(CRUX__is_equal(one_max.value, one), "Must be equal to %"IU32_FMT".", one);
  ok(CRUX__is_equal(one_one.value, nil), "Must be equal to %"IU32_FMT".", nil);
  CRUX__trace_clean(&max_max.trace);
  CRUX__trace_clean(&max_min.trace);
  CRUX__trace_clean(&max_nil.trace);
  CRUX__trace_clean(&max_one.trace);
  CRUX__trace_clean(&min_max.trace);
  CRUX__trace_clean(&min_min.trace);
  CRUX__trace_clean(&min_nil.trace);
  CRUX__trace_clean(&min_one.trace);
  CRUX__trace_clean(&nil_max.trace);
  CRUX__trace_clean(&nil_min.trace);
  CRUX__trace_clean(&nil_nil.trace);
  CRUX__trace_clean(&nil_one.trace);
  CRUX__trace_clean(&one_max.trace);
  CRUX__trace_clean(&one_min.trace);
  CRUX__trace_clean(&one_nil.trace);
  CRUX__trace_clean(&one_one.trace);
}


void CRUX__mod_iu64_tests (void) {
  const IU64 max = IU64_MAX;
  const IU64 min = IU64_MIN;
  const IU64 nil = as_iu64(0);
  const IU64 one = as_iu64(1);
  CRUX__ResultIU64 max_max = CRUX__mod(max, max);
  CRUX__ResultIU64 max_min = CRUX__mod(max, min);
  CRUX__ResultIU64 max_nil = CRUX__mod(max, nil);
  CRUX__ResultIU64 max_one = CRUX__mod(max, one);
  CRUX__ResultIU64 min_max = CRUX__mod(min, max);
  CRUX__ResultIU64 min_min = CRUX__mod(min, min);
  CRUX__ResultIU64 min_nil = CRUX__mod(min, nil);
  CRUX__ResultIU64 min_one = CRUX__mod(min, one);
  CRUX__ResultIU64 nil_max = CRUX__mod(nil, max);
  CRUX__ResultIU64 nil_min = CRUX__mod(nil, min);
  CRUX__ResultIU64 nil_nil = CRUX__mod(nil, nil);
  CRUX__ResultIU64 nil_one = CRUX__mod(nil, one);
  CRUX__ResultIU64 one_max = CRUX__mod(one, max);
  CRUX__ResultIU64 one_min = CRUX__mod(one, min);
  CRUX__ResultIU64 one_nil = CRUX__mod(one, nil);
  CRUX__ResultIU64 one_one = CRUX__mod(one, one);
  ok(CRUX__trace_check(max_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(max_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(max_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(max_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(min_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(min_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(min_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(nil_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(nil_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(nil_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(one_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(one_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(one_one.trace), "Must not have an error.");
  ok(CRUX__is_equal(max_max.value, nil), "Must be equal to %"IU64_FMT".", nil);
  ok(CRUX__is_equal(max_one.value, nil), "Must be equal to %"IU64_FMT".", nil);
  ok(CRUX__is_equal(min_max.value, nil), "Must be equal to %"IU64_FMT".", nil);
  ok(CRUX__is_equal(min_one.value, nil), "Must be equal to %"IU64_FMT".", nil);
  ok(CRUX__is_equal(nil_max.value, nil), "Must be equal to %"IU64_FMT".", nil);
  ok(CRUX__is_equal(nil_one.value, nil), "Must be equal to %"IU64_FMT".", nil);
  ok(CRUX__is_equal(one_max.value, one), "Must be equal to %"IU64_FMT".", one);
  ok(CRUX__is_equal(one_one.value, nil), "Must be equal to %"IU64_FMT".", nil);
  CRUX__trace_clean(&max_max.trace);
  CRUX__trace_clean(&max_min.trace);
  CRUX__trace_clean(&max_nil.trace);
  CRUX__trace_clean(&max_one.trace);
  CRUX__trace_clean(&min_max.trace);
  CRUX__trace_clean(&min_min.trace);
  CRUX__trace_clean(&min_nil.trace);
  CRUX__trace_clean(&min_one.trace);
  CRUX__trace_clean(&nil_max.trace);
  CRUX__trace_clean(&nil_min.trace);
  CRUX__trace_clean(&nil_nil.trace);
  CRUX__trace_clean(&nil_one.trace);
  CRUX__trace_clean(&one_max.trace);
  CRUX__trace_clean(&one_min.trace);
  CRUX__trace_clean(&one_nil.trace);
  CRUX__trace_clean(&one_one.trace);
}


void CRUX__mod_is08_tests (void) {
  const IS08 max = IS08_MAX;
  const IS08 min = IS08_MIN;
  const IS08 nil = as_is08(0);
  const IS08 one = as_is08(1);
  const IS08 neg = as_is08(-1);
  const IS08 foo = (IS08)(IS08_MAX - 1);
  CRUX__ResultIS08 max_max = CRUX__mod(max, max);
  CRUX__ResultIS08 min_max = CRUX__mod(min, max);
  CRUX__ResultIS08 nil_max = CRUX__mod(nil, max);
  CRUX__ResultIS08 one_max = CRUX__mod(one, max);
  CRUX__ResultIS08 neg_max = CRUX__mod(neg, max);
  CRUX__ResultIS08 max_min = CRUX__mod(max, min);
  CRUX__ResultIS08 min_min = CRUX__mod(min, min);
  CRUX__ResultIS08 nil_min = CRUX__mod(nil, min);
  CRUX__ResultIS08 one_min = CRUX__mod(one, min);
  CRUX__ResultIS08 neg_min = CRUX__mod(neg, min);
  CRUX__ResultIS08 max_nil = CRUX__mod(max, nil);
  CRUX__ResultIS08 min_nil = CRUX__mod(min, nil);
  CRUX__ResultIS08 nil_nil = CRUX__mod(nil, nil);
  CRUX__ResultIS08 one_nil = CRUX__mod(one, nil);
  CRUX__ResultIS08 neg_nil = CRUX__mod(neg, nil);
  CRUX__ResultIS08 max_one = CRUX__mod(max, one);
  CRUX__ResultIS08 min_one = CRUX__mod(min, one);
  CRUX__ResultIS08 nil_one = CRUX__mod(nil, one);
  CRUX__ResultIS08 one_one = CRUX__mod(one, one);
  CRUX__ResultIS08 neg_one = CRUX__mod(neg, one);
  CRUX__ResultIS08 max_neg = CRUX__mod(max, neg);
  CRUX__ResultIS08 min_neg = CRUX__mod(min, neg);
  CRUX__ResultIS08 nil_neg = CRUX__mod(nil, neg);
  CRUX__ResultIS08 one_neg = CRUX__mod(one, neg);
  CRUX__ResultIS08 neg_neg = CRUX__mod(neg, neg);
  ok(CRUX__trace_check(max_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(min_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(nil_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(one_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(neg_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(max_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(neg_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(max_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(neg_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(max_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(min_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(nil_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(one_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(neg_one.trace), "Must not have an error.");
  ok(!CRUX__trace_check(max_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(neg_neg.trace), "Must have an error.");
  ok(CRUX__is_equal(max_max.value, nil), "Must be equal to %"IS08_FMT".", nil);
  ok(CRUX__is_equal(min_max.value, foo), "Must be equal to %"IS08_FMT".", foo);
  ok(CRUX__is_equal(nil_max.value, nil), "Must be equal to %"IS08_FMT".", nil);
  ok(CRUX__is_equal(one_max.value, one), "Must be equal to %"IS08_FMT".", one);
  ok(CRUX__is_equal(neg_max.value, foo), "Must be equal to %"IS08_FMT".", foo);
  ok(CRUX__is_equal(max_one.value, nil), "Must be equal to %"IS08_FMT".", nil);
  ok(CRUX__is_equal(min_one.value, nil), "Must be equal to %"IS08_FMT".", nil);
  ok(CRUX__is_equal(nil_one.value, nil), "Must be equal to %"IS08_FMT".", nil);
  ok(CRUX__is_equal(one_one.value, nil), "Must be equal to %"IS08_FMT".", nil);
  ok(CRUX__is_equal(neg_one.value, nil), "Must be equal to %"IS08_FMT".", nil);
}


void CRUX__mod_is16_tests (void) {
  const IS16 max = IS16_MAX;
  const IS16 min = IS16_MIN;
  const IS16 nil = as_is16(0);
  const IS16 one = as_is16(1);
  const IS16 neg = as_is16(-1);
  const IS16 foo = (IS16)(IS16_MAX - 1);
  CRUX__ResultIS16 max_max = CRUX__mod(max, max);
  CRUX__ResultIS16 min_max = CRUX__mod(min, max);
  CRUX__ResultIS16 nil_max = CRUX__mod(nil, max);
  CRUX__ResultIS16 one_max = CRUX__mod(one, max);
  CRUX__ResultIS16 neg_max = CRUX__mod(neg, max);
  CRUX__ResultIS16 max_min = CRUX__mod(max, min);
  CRUX__ResultIS16 min_min = CRUX__mod(min, min);
  CRUX__ResultIS16 nil_min = CRUX__mod(nil, min);
  CRUX__ResultIS16 one_min = CRUX__mod(one, min);
  CRUX__ResultIS16 neg_min = CRUX__mod(neg, min);
  CRUX__ResultIS16 max_nil = CRUX__mod(max, nil);
  CRUX__ResultIS16 min_nil = CRUX__mod(min, nil);
  CRUX__ResultIS16 nil_nil = CRUX__mod(nil, nil);
  CRUX__ResultIS16 one_nil = CRUX__mod(one, nil);
  CRUX__ResultIS16 neg_nil = CRUX__mod(neg, nil);
  CRUX__ResultIS16 max_one = CRUX__mod(max, one);
  CRUX__ResultIS16 min_one = CRUX__mod(min, one);
  CRUX__ResultIS16 nil_one = CRUX__mod(nil, one);
  CRUX__ResultIS16 one_one = CRUX__mod(one, one);
  CRUX__ResultIS16 neg_one = CRUX__mod(neg, one);
  CRUX__ResultIS16 max_neg = CRUX__mod(max, neg);
  CRUX__ResultIS16 min_neg = CRUX__mod(min, neg);
  CRUX__ResultIS16 nil_neg = CRUX__mod(nil, neg);
  CRUX__ResultIS16 one_neg = CRUX__mod(one, neg);
  CRUX__ResultIS16 neg_neg = CRUX__mod(neg, neg);
  ok(CRUX__trace_check(max_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(min_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(nil_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(one_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(neg_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(max_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(neg_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(max_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(neg_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(max_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(min_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(nil_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(one_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(neg_one.trace), "Must not have an error.");
  ok(!CRUX__trace_check(max_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(neg_neg.trace), "Must have an error.");
  ok(CRUX__is_equal(max_max.value, nil), "Must be equal to %"IS16_FMT".", nil);
  ok(CRUX__is_equal(min_max.value, foo), "Must be equal to %"IS16_FMT".", foo);
  ok(CRUX__is_equal(nil_max.value, nil), "Must be equal to %"IS16_FMT".", nil);
  ok(CRUX__is_equal(one_max.value, one), "Must be equal to %"IS16_FMT".", one);
  ok(CRUX__is_equal(neg_max.value, foo), "Must be equal to %"IS16_FMT".", foo);
  ok(CRUX__is_equal(max_one.value, nil), "Must be equal to %"IS16_FMT".", nil);
  ok(CRUX__is_equal(min_one.value, nil), "Must be equal to %"IS16_FMT".", nil);
  ok(CRUX__is_equal(nil_one.value, nil), "Must be equal to %"IS16_FMT".", nil);
  ok(CRUX__is_equal(one_one.value, nil), "Must be equal to %"IS16_FMT".", nil);
  ok(CRUX__is_equal(neg_one.value, nil), "Must be equal to %"IS16_FMT".", nil);
}


void CRUX__mod_is32_tests (void) {
  const IS32 max = IS32_MAX;
  const IS32 min = IS32_MIN;
  const IS32 nil = as_is32(0);
  const IS32 one = as_is32(1);
  const IS32 neg = as_is32(-1);
  const IS32 foo = (IS32)(IS32_MAX - 1);
  CRUX__ResultIS32 max_max = CRUX__mod(max, max);
  CRUX__ResultIS32 min_max = CRUX__mod(min, max);
  CRUX__ResultIS32 nil_max = CRUX__mod(nil, max);
  CRUX__ResultIS32 one_max = CRUX__mod(one, max);
  CRUX__ResultIS32 neg_max = CRUX__mod(neg, max);
  CRUX__ResultIS32 max_min = CRUX__mod(max, min);
  CRUX__ResultIS32 min_min = CRUX__mod(min, min);
  CRUX__ResultIS32 nil_min = CRUX__mod(nil, min);
  CRUX__ResultIS32 one_min = CRUX__mod(one, min);
  CRUX__ResultIS32 neg_min = CRUX__mod(neg, min);
  CRUX__ResultIS32 max_nil = CRUX__mod(max, nil);
  CRUX__ResultIS32 min_nil = CRUX__mod(min, nil);
  CRUX__ResultIS32 nil_nil = CRUX__mod(nil, nil);
  CRUX__ResultIS32 one_nil = CRUX__mod(one, nil);
  CRUX__ResultIS32 neg_nil = CRUX__mod(neg, nil);
  CRUX__ResultIS32 max_one = CRUX__mod(max, one);
  CRUX__ResultIS32 min_one = CRUX__mod(min, one);
  CRUX__ResultIS32 nil_one = CRUX__mod(nil, one);
  CRUX__ResultIS32 one_one = CRUX__mod(one, one);
  CRUX__ResultIS32 neg_one = CRUX__mod(neg, one);
  CRUX__ResultIS32 max_neg = CRUX__mod(max, neg);
  CRUX__ResultIS32 min_neg = CRUX__mod(min, neg);
  CRUX__ResultIS32 nil_neg = CRUX__mod(nil, neg);
  CRUX__ResultIS32 one_neg = CRUX__mod(one, neg);
  CRUX__ResultIS32 neg_neg = CRUX__mod(neg, neg);
  ok(CRUX__trace_check(max_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(min_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(nil_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(one_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(neg_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(max_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(neg_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(max_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(neg_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(max_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(min_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(nil_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(one_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(neg_one.trace), "Must not have an error.");
  ok(!CRUX__trace_check(max_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(neg_neg.trace), "Must have an error.");
  ok(CRUX__is_equal(max_max.value, nil), "Must be equal to %"IS32_FMT".", nil);
  ok(CRUX__is_equal(min_max.value, foo), "Must be equal to %"IS32_FMT".", foo);
  ok(CRUX__is_equal(nil_max.value, nil), "Must be equal to %"IS32_FMT".", nil);
  ok(CRUX__is_equal(one_max.value, one), "Must be equal to %"IS32_FMT".", one);
  ok(CRUX__is_equal(neg_max.value, foo), "Must be equal to %"IS32_FMT".", foo);
  ok(CRUX__is_equal(max_one.value, nil), "Must be equal to %"IS32_FMT".", nil);
  ok(CRUX__is_equal(min_one.value, nil), "Must be equal to %"IS32_FMT".", nil);
  ok(CRUX__is_equal(nil_one.value, nil), "Must be equal to %"IS32_FMT".", nil);
  ok(CRUX__is_equal(one_one.value, nil), "Must be equal to %"IS32_FMT".", nil);
  ok(CRUX__is_equal(neg_one.value, nil), "Must be equal to %"IS32_FMT".", nil);
}


void CRUX__mod_is64_tests (void) {
  const IS64 max = IS64_MAX;
  const IS64 min = IS64_MIN;
  const IS64 nil = as_is64(0);
  const IS64 one = as_is64(1);
  const IS64 neg = as_is64(-1);
  const IS64 foo = (IS64)(IS64_MAX - 1);
  CRUX__ResultIS64 max_max = CRUX__mod(max, max);
  CRUX__ResultIS64 min_max = CRUX__mod(min, max);
  CRUX__ResultIS64 nil_max = CRUX__mod(nil, max);
  CRUX__ResultIS64 one_max = CRUX__mod(one, max);
  CRUX__ResultIS64 neg_max = CRUX__mod(neg, max);
  CRUX__ResultIS64 max_min = CRUX__mod(max, min);
  CRUX__ResultIS64 min_min = CRUX__mod(min, min);
  CRUX__ResultIS64 nil_min = CRUX__mod(nil, min);
  CRUX__ResultIS64 one_min = CRUX__mod(one, min);
  CRUX__ResultIS64 neg_min = CRUX__mod(neg, min);
  CRUX__ResultIS64 max_nil = CRUX__mod(max, nil);
  CRUX__ResultIS64 min_nil = CRUX__mod(min, nil);
  CRUX__ResultIS64 nil_nil = CRUX__mod(nil, nil);
  CRUX__ResultIS64 one_nil = CRUX__mod(one, nil);
  CRUX__ResultIS64 neg_nil = CRUX__mod(neg, nil);
  CRUX__ResultIS64 max_one = CRUX__mod(max, one);
  CRUX__ResultIS64 min_one = CRUX__mod(min, one);
  CRUX__ResultIS64 nil_one = CRUX__mod(nil, one);
  CRUX__ResultIS64 one_one = CRUX__mod(one, one);
  CRUX__ResultIS64 neg_one = CRUX__mod(neg, one);
  CRUX__ResultIS64 max_neg = CRUX__mod(max, neg);
  CRUX__ResultIS64 min_neg = CRUX__mod(min, neg);
  CRUX__ResultIS64 nil_neg = CRUX__mod(nil, neg);
  CRUX__ResultIS64 one_neg = CRUX__mod(one, neg);
  CRUX__ResultIS64 neg_neg = CRUX__mod(neg, neg);
  ok(CRUX__trace_check(max_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(min_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(nil_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(one_max.trace), "Must not have an error.");
  ok(CRUX__trace_check(neg_max.trace), "Must not have an error.");
  ok(!CRUX__trace_check(max_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(neg_min.trace), "Must have an error.");
  ok(!CRUX__trace_check(max_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_nil.trace), "Must have an error.");
  ok(!CRUX__trace_check(neg_nil.trace), "Must have an error.");
  ok(CRUX__trace_check(max_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(min_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(nil_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(one_one.trace), "Must not have an error.");
  ok(CRUX__trace_check(neg_one.trace), "Must not have an error.");
  ok(!CRUX__trace_check(max_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(min_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(nil_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(one_neg.trace), "Must have an error.");
  ok(!CRUX__trace_check(neg_neg.trace), "Must have an error.");
  ok(CRUX__is_equal(max_max.value, nil), "Must be equal to %"IS64_FMT".", nil);
  ok(CRUX__is_equal(min_max.value, foo), "Must be equal to %"IS64_FMT".", foo);
  ok(CRUX__is_equal(nil_max.value, nil), "Must be equal to %"IS64_FMT".", nil);
  ok(CRUX__is_equal(one_max.value, one), "Must be equal to %"IS64_FMT".", one);
  ok(CRUX__is_equal(neg_max.value, foo), "Must be equal to %"IS64_FMT".", foo);
  ok(CRUX__is_equal(max_one.value, nil), "Must be equal to %"IS64_FMT".", nil);
  ok(CRUX__is_equal(min_one.value, nil), "Must be equal to %"IS64_FMT".", nil);
  ok(CRUX__is_equal(nil_one.value, nil), "Must be equal to %"IS64_FMT".", nil);
  ok(CRUX__is_equal(one_one.value, nil), "Must be equal to %"IS64_FMT".", nil);
  ok(CRUX__is_equal(neg_one.value, nil), "Must be equal to %"IS64_FMT".", nil);
}


int main (int argc, char *argv[]) {
  plan(236);
  CRUX__mod_iu08_tests();
  CRUX__mod_iu16_tests();
  CRUX__mod_iu32_tests();
  CRUX__mod_iu64_tests();
  CRUX__mod_is08_tests();
  CRUX__mod_is16_tests();
  CRUX__mod_is32_tests();
  CRUX__mod_is64_tests();
  done_testing();
  return EXIT_SUCCESS;
}
