#include <string.h>
#include <talloc.h>
#include <tap.h>
#include "./../src/core/order.h"


void CRUX__is_less_tests (void) {
  const Char a_char = CHAR_MIN;
  const Char b_char = CHAR_MAX;
  const Size a_size = SIZE_MIN;
  const Size b_size = SIZE_MAX;
  const IU08 a_iu08 = IU08_MIN;
  const IU08 b_iu08 = IU08_MAX;
  const IU16 a_iu16 = IU16_MIN;
  const IU16 b_iu16 = IU16_MAX;
  const IU32 a_iu32 = IU32_MIN;
  const IU32 b_iu32 = IU32_MAX;
  const IU64 a_iu64 = IU64_MIN;
  const IU64 b_iu64 = IU64_MAX;
  const IS08 a_is08 = IS08_MIN;
  const IS08 b_is08 = IS08_MAX;
  const IS16 a_is16 = IS16_MIN;
  const IS16 b_is16 = IS16_MAX;
  const IS32 a_is32 = IS32_MIN;
  const IS32 b_is32 = IS32_MAX;
  const IS64 a_is64 = IS64_MIN;
  const IS64 b_is64 = IS64_MAX;
  ok(!CRUX__is_less_char(a_char, a_char), "Must not be less.");
  ok(CRUX__is_less_char(a_char, b_char), "Must be less.");
  ok(!CRUX__is_less_char(b_char, a_char), "Must not be less.");
  ok(!CRUX__is_less_char(b_char, b_char), "Must not be less.");
  ok(!CRUX__is_less_size(a_size, a_size), "Must not be less.");
  ok(CRUX__is_less_size(a_size, b_size), "Must be less.");
  ok(!CRUX__is_less_size(b_size, a_size), "Must not be less.");
  ok(!CRUX__is_less_size(b_size, b_size), "Must not be less.");
  ok(!CRUX__is_less(a_iu08, a_iu08), "Must not be less.");
  ok(CRUX__is_less(a_iu08, b_iu08), "Must be less.");
  ok(!CRUX__is_less(b_iu08, a_iu08), "Must not be less.");
  ok(!CRUX__is_less(b_iu08, b_iu08), "Must not be less.");
  ok(!CRUX__is_less(a_iu16, a_iu16), "Must not be less.");
  ok(CRUX__is_less(a_iu16, b_iu16), "Must be less.");
  ok(!CRUX__is_less(b_iu16, a_iu16), "Must not be less.");
  ok(!CRUX__is_less(b_iu16, b_iu16), "Must not be less.");
  ok(!CRUX__is_less(a_iu32, a_iu32), "Must not be less.");
  ok(CRUX__is_less(a_iu32, b_iu32), "Must be less.");
  ok(!CRUX__is_less(b_iu32, a_iu32), "Must not be less.");
  ok(!CRUX__is_less(b_iu32, b_iu32), "Must not be less.");
  ok(!CRUX__is_less(a_iu64, a_iu64), "Must not be less.");
  ok(CRUX__is_less(a_iu64, b_iu64), "Must be less.");
  ok(!CRUX__is_less(b_iu64, a_iu64), "Must not be less.");
  ok(!CRUX__is_less(b_iu64, b_iu64), "Must not be less.");
  ok(!CRUX__is_less(a_is08, a_is08), "Must not be less.");
  ok(CRUX__is_less(a_is08, b_is08), "Must be less.");
  ok(!CRUX__is_less(b_is08, a_is08), "Must not be less.");
  ok(!CRUX__is_less(b_is08, b_is08), "Must not be less.");
  ok(!CRUX__is_less(a_is16, a_is16), "Must not be less.");
  ok(CRUX__is_less(a_is16, b_is16), "Must be less.");
  ok(!CRUX__is_less(b_is16, a_is16), "Must not be less.");
  ok(!CRUX__is_less(b_is16, b_is16), "Must not be less.");
  ok(!CRUX__is_less(a_is32, a_is32), "Must not be less.");
  ok(CRUX__is_less(a_is32, b_is32), "Must be less.");
  ok(!CRUX__is_less(b_is32, a_is32), "Must not be less.");
  ok(!CRUX__is_less(b_is32, b_is32), "Must not be less.");
  ok(!CRUX__is_less(a_is64, a_is64), "Must not be less.");
  ok(CRUX__is_less(a_is64, b_is64), "Must be less.");
  ok(!CRUX__is_less(b_is64, a_is64), "Must not be less.");
  ok(!CRUX__is_less(b_is64, b_is64), "Must not be less.");
}


void CRUX__is_less_equal_tests (void) {
  const Char a_char = CHAR_MIN;
  const Char b_char = CHAR_MAX;
  const Size a_size = SIZE_MIN;
  const Size b_size = SIZE_MAX;
  const IU08 a_iu08 = IU08_MIN;
  const IU08 b_iu08 = IU08_MAX;
  const IU16 a_iu16 = IU16_MIN;
  const IU16 b_iu16 = IU16_MAX;
  const IU32 a_iu32 = IU32_MIN;
  const IU32 b_iu32 = IU32_MAX;
  const IU64 a_iu64 = IU64_MIN;
  const IU64 b_iu64 = IU64_MAX;
  const IS08 a_is08 = IS08_MIN;
  const IS08 b_is08 = IS08_MAX;
  const IS16 a_is16 = IS16_MIN;
  const IS16 b_is16 = IS16_MAX;
  const IS32 a_is32 = IS32_MIN;
  const IS32 b_is32 = IS32_MAX;
  const IS64 a_is64 = IS64_MIN;
  const IS64 b_is64 = IS64_MAX;
  ok(CRUX__is_less_equal_char(a_char, a_char), "Must be less or equal.");
  ok(CRUX__is_less_equal_char(a_char, b_char), "Must be less or equal.");
  ok(!CRUX__is_less_equal_char(b_char, a_char), "Must not be less or equal.");
  ok(CRUX__is_less_equal_char(b_char, b_char), "Must be less or equal.");
  ok(CRUX__is_less_equal_size(a_size, a_size), "Must be less or equal.");
  ok(CRUX__is_less_equal_size(a_size, b_size), "Must be less or equal.");
  ok(!CRUX__is_less_equal_size(b_size, a_size), "Must not be less or equal.");
  ok(CRUX__is_less_equal_size(b_size, b_size), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_iu08, a_iu08), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_iu08, b_iu08), "Must be less or equal.");
  ok(!CRUX__is_less_equal(b_iu08, a_iu08), "Must not be less or equal.");
  ok(CRUX__is_less_equal(b_iu08, b_iu08), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_iu16, a_iu16), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_iu16, b_iu16), "Must be less or equal.");
  ok(!CRUX__is_less_equal(b_iu16, a_iu16), "Must not be less or equal.");
  ok(CRUX__is_less_equal(b_iu16, b_iu16), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_iu32, a_iu32), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_iu32, b_iu32), "Must be less or equal.");
  ok(!CRUX__is_less_equal(b_iu32, a_iu32), "Must not be less or equal.");
  ok(CRUX__is_less_equal(b_iu32, b_iu32), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_iu64, a_iu64), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_iu64, b_iu64), "Must be less or equal.");
  ok(!CRUX__is_less_equal(b_iu64, a_iu64), "Must not be less or equal.");
  ok(CRUX__is_less_equal(b_iu64, b_iu64), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_is08, a_is08), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_is08, b_is08), "Must be less or equal.");
  ok(!CRUX__is_less_equal(b_is08, a_is08), "Must not be less or equal.");
  ok(CRUX__is_less_equal(b_is08, b_is08), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_is16, a_is16), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_is16, b_is16), "Must be less or equal.");
  ok(!CRUX__is_less_equal(b_is16, a_is16), "Must not be less or equal.");
  ok(CRUX__is_less_equal(b_is16, b_is16), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_is32, a_is32), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_is32, b_is32), "Must be less or equal.");
  ok(!CRUX__is_less_equal(b_is32, a_is32), "Must not be less or equal.");
  ok(CRUX__is_less_equal(b_is32, b_is32), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_is64, a_is64), "Must be less or equal.");
  ok(CRUX__is_less_equal(a_is64, b_is64), "Must be less or equal.");
  ok(!CRUX__is_less_equal(b_is64, a_is64), "Must not be less.");
  ok(CRUX__is_less_equal(b_is64, b_is64), "Must be less or equal.");
}


void CRUX__is_equal_tests (void) {
  const Char a_char = CHAR_MIN;
  const Char b_char = CHAR_MAX;
  const Size a_size = SIZE_MIN;
  const Size b_size = SIZE_MAX;
  const IU08 a_iu08 = IU08_MIN;
  const IU08 b_iu08 = IU08_MAX;
  const IU16 a_iu16 = IU16_MIN;
  const IU16 b_iu16 = IU16_MAX;
  const IU32 a_iu32 = IU32_MIN;
  const IU32 b_iu32 = IU32_MAX;
  const IU64 a_iu64 = IU64_MIN;
  const IU64 b_iu64 = IU64_MAX;
  const IS08 a_is08 = IS08_MIN;
  const IS08 b_is08 = IS08_MAX;
  const IS16 a_is16 = IS16_MIN;
  const IS16 b_is16 = IS16_MAX;
  const IS32 a_is32 = IS32_MIN;
  const IS32 b_is32 = IS32_MAX;
  const IS64 a_is64 = IS64_MIN;
  const IS64 b_is64 = IS64_MAX;
  ok(CRUX__is_equal_char(a_char, a_char), "Must be equal.");
  ok(!CRUX__is_equal_char(a_char, b_char), "Must not be equal.");
  ok(!CRUX__is_equal_char(b_char, a_char), "Must not be equal.");
  ok(CRUX__is_equal_char(b_char, b_char), "Must equal.");
  ok(CRUX__is_equal_size(a_size, a_size), "Must be equal.");
  ok(!CRUX__is_equal_size(a_size, b_size), "Must not be equal.");
  ok(!CRUX__is_equal_size(b_size, a_size), "Must not be equal.");
  ok(CRUX__is_equal_size(b_size, b_size), "Must equal.");
  ok(CRUX__is_equal(a_iu08, a_iu08), "Must be equal.");
  ok(!CRUX__is_equal(a_iu08, b_iu08), "Must not be equal.");
  ok(!CRUX__is_equal(b_iu08, a_iu08), "Must not be equal.");
  ok(CRUX__is_equal(b_iu08, b_iu08), "Must equal.");
  ok(CRUX__is_equal(a_iu16, a_iu16), "Must be equal.");
  ok(!CRUX__is_equal(a_iu16, b_iu16), "Must not be equal.");
  ok(!CRUX__is_equal(b_iu16, a_iu16), "Must not be equal.");
  ok(CRUX__is_equal(b_iu16, b_iu16), "Must equal.");
  ok(CRUX__is_equal(a_iu32, a_iu32), "Must be equal.");
  ok(!CRUX__is_equal(a_iu32, b_iu32), "Must not be equal.");
  ok(!CRUX__is_equal(b_iu32, a_iu32), "Must not be equal.");
  ok(CRUX__is_equal(b_iu32, b_iu32), "Must equal.");
  ok(CRUX__is_equal(a_iu64, a_iu64), "Must be equal.");
  ok(!CRUX__is_equal(a_iu64, b_iu64), "Must not be equal.");
  ok(!CRUX__is_equal(b_iu64, a_iu64), "Must not be equal.");
  ok(CRUX__is_equal(b_iu64, b_iu64), "Must equal.");
  ok(CRUX__is_equal(a_is08, a_is08), "Must be equal.");
  ok(!CRUX__is_equal(a_is08, b_is08), "Must not be equal.");
  ok(!CRUX__is_equal(b_is08, a_is08), "Must not be equal.");
  ok(CRUX__is_equal(b_is08, b_is08), "Must equal.");
  ok(CRUX__is_equal(a_is16, a_is16), "Must not be less.");
  ok(!CRUX__is_equal(a_is16, b_is16), "Must be less.");
  ok(!CRUX__is_equal(b_is16, a_is16), "Must not be less.");
  ok(CRUX__is_equal(b_is16, b_is16), "Must not be less.");
  ok(CRUX__is_equal(a_is32, a_is32), "Must be equal.");
  ok(!CRUX__is_equal(a_is32, b_is32), "Must not be equal.");
  ok(!CRUX__is_equal(b_is32, a_is32), "Must not be equal.");
  ok(CRUX__is_equal(b_is32, b_is32), "Must equal.");
  ok(CRUX__is_equal(a_is64, a_is64), "Must be equal.");
  ok(!CRUX__is_equal(a_is64, b_is64), "Must not be equal.");
  ok(!CRUX__is_equal(b_is64, a_is64), "Must not be equal.");
  ok(CRUX__is_equal(b_is64, b_is64), "Must equal.");
}


void CRUX__is_greater_equal_tests (void) {
  const Char a_char = CHAR_MIN;
  const Char b_char = CHAR_MAX;
  const Size a_size = SIZE_MIN;
  const Size b_size = SIZE_MAX;
  const IU08 a_iu08 = IU08_MIN;
  const IU08 b_iu08 = IU08_MAX;
  const IU16 a_iu16 = IU16_MIN;
  const IU16 b_iu16 = IU16_MAX;
  const IU32 a_iu32 = IU32_MIN;
  const IU32 b_iu32 = IU32_MAX;
  const IU64 a_iu64 = IU64_MIN;
  const IU64 b_iu64 = IU64_MAX;
  const IS08 a_is08 = IS08_MIN;
  const IS08 b_is08 = IS08_MAX;
  const IS16 a_is16 = IS16_MIN;
  const IS16 b_is16 = IS16_MAX;
  const IS32 a_is32 = IS32_MIN;
  const IS32 b_is32 = IS32_MAX;
  const IS64 a_is64 = IS64_MIN;
  const IS64 b_is64 = IS64_MAX;
  ok(CRUX__is_greater_equal_char(a_char, a_char), "Must be greater or equal.");
  ok(!CRUX__is_greater_equal_char(a_char, b_char), "Must not be greater or equal.");
  ok(CRUX__is_greater_equal_char(b_char, a_char), "Must be greater or equal.");
  ok(CRUX__is_greater_equal_char(b_char, b_char), "Must be greater or equal.");
  ok(CRUX__is_greater_equal_size(a_size, a_size), "Must be greater or equal.");
  ok(!CRUX__is_greater_equal_size(a_size, b_size), "Must not be greater or equal.");
  ok(CRUX__is_greater_equal_size(b_size, a_size), "Must be greater or equal.");
  ok(CRUX__is_greater_equal_size(b_size, b_size), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(a_iu08, a_iu08), "Must be greater or equal.");
  ok(!CRUX__is_greater_equal(a_iu08, b_iu08), "Must not be greater or equal.");
  ok(CRUX__is_greater_equal(b_iu08, a_iu08), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(b_iu08, b_iu08), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(a_iu16, a_iu16), "Must be greater or equal.");
  ok(!CRUX__is_greater_equal(a_iu16, b_iu16), "Must not be greater or equal.");
  ok(CRUX__is_greater_equal(b_iu16, a_iu16), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(b_iu16, b_iu16), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(a_iu32, a_iu32), "Must be greater or equal.");
  ok(!CRUX__is_greater_equal(a_iu32, b_iu32), "Must not be greater or equal.");
  ok(CRUX__is_greater_equal(b_iu32, a_iu32), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(b_iu32, b_iu32), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(a_iu64, a_iu64), "Must be greater or equal.");
  ok(!CRUX__is_greater_equal(a_iu64, b_iu64), "Must not be greater or equal.");
  ok(CRUX__is_greater_equal(b_iu64, a_iu64), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(b_iu64, b_iu64), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(a_is08, a_is08), "Must be greater or equal.");
  ok(!CRUX__is_greater_equal(a_is08, b_is08), "Must not be greater or equal.");
  ok(CRUX__is_greater_equal(b_is08, a_is08), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(b_is08, b_is08), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(a_is16, a_is16), "Must be greater or equal.");
  ok(!CRUX__is_greater_equal(a_is16, b_is16), "Must not be greater or equal.");
  ok(CRUX__is_greater_equal(b_is16, a_is16), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(b_is16, b_is16), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(a_is32, a_is32), "Must be greater or equal.");
  ok(!CRUX__is_greater_equal(a_is32, b_is32), "Must not be greater or equal.");
  ok(CRUX__is_greater_equal(b_is32, a_is32), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(b_is32, b_is32), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(a_is64, a_is64), "Must be greater or equal.");
  ok(!CRUX__is_greater_equal(a_is64, b_is64), "Must not be greater or equal.");
  ok(CRUX__is_greater_equal(b_is64, a_is64), "Must be greater or equal.");
  ok(CRUX__is_greater_equal(b_is64, b_is64), "Must be greater or equal.");
}


void CRUX__is_greater_tests (void) {
  const Char a_char = CHAR_MIN;
  const Char b_char = CHAR_MAX;
  const Size a_size = SIZE_MIN;
  const Size b_size = SIZE_MAX;
  const IU08 a_iu08 = IU08_MIN;
  const IU08 b_iu08 = IU08_MAX;
  const IU16 a_iu16 = IU16_MIN;
  const IU16 b_iu16 = IU16_MAX;
  const IU32 a_iu32 = IU32_MIN;
  const IU32 b_iu32 = IU32_MAX;
  const IU64 a_iu64 = IU64_MIN;
  const IU64 b_iu64 = IU64_MAX;
  const IS08 a_is08 = IS08_MIN;
  const IS08 b_is08 = IS08_MAX;
  const IS16 a_is16 = IS16_MIN;
  const IS16 b_is16 = IS16_MAX;
  const IS32 a_is32 = IS32_MIN;
  const IS32 b_is32 = IS32_MAX;
  const IS64 a_is64 = IS64_MIN;
  const IS64 b_is64 = IS64_MAX;
  ok(!CRUX__is_greater_char(a_char, a_char), "Must not be greater.");
  ok(!CRUX__is_greater_char(a_char, b_char), "Must not be greater.");
  ok(CRUX__is_greater_char(b_char, a_char), "Must be greater.");
  ok(!CRUX__is_greater_char(b_char, b_char), "Must not be greater.");
  ok(!CRUX__is_greater_size(a_size, a_size), "Must not be greater.");
  ok(!CRUX__is_greater_size(a_size, b_size), "Must not be greater.");
  ok(CRUX__is_greater_size(b_size, a_size), "Must be greater.");
  ok(!CRUX__is_greater_size(b_size, b_size), "Must not be greater.");
  ok(!CRUX__is_greater(a_iu08, a_iu08), "Must not be greater.");
  ok(!CRUX__is_greater(a_iu08, b_iu08), "Must not be greater.");
  ok(CRUX__is_greater(b_iu08, a_iu08), "Must be greater.");
  ok(!CRUX__is_greater(b_iu08, b_iu08), "Must not be greater.");
  ok(!CRUX__is_greater(a_iu16, a_iu16), "Must not be greater.");
  ok(!CRUX__is_greater(a_iu16, b_iu16), "Must not be greater.");
  ok(CRUX__is_greater(b_iu16, a_iu16), "Must be greater.");
  ok(!CRUX__is_greater(b_iu16, b_iu16), "Must not be greater.");
  ok(!CRUX__is_greater(a_iu32, a_iu32), "Must not be greater.");
  ok(!CRUX__is_greater(a_iu32, b_iu32), "Must not be greater.");
  ok(CRUX__is_greater(b_iu32, a_iu32), "Must be greater.");
  ok(!CRUX__is_greater(b_iu32, b_iu32), "Must not be greater.");
  ok(!CRUX__is_greater(a_iu64, a_iu64), "Must not be greater.");
  ok(!CRUX__is_greater(a_iu64, b_iu64), "Must not be greater.");
  ok(CRUX__is_greater(b_iu64, a_iu64), "Must be greater.");
  ok(!CRUX__is_greater(b_iu64, b_iu64), "Must not be greater.");
  ok(!CRUX__is_greater(a_is08, a_is08), "Must not be greater.");
  ok(!CRUX__is_greater(a_is08, b_is08), "Must not be greater.");
  ok(CRUX__is_greater(b_is08, a_is08), "Must be greater.");
  ok(!CRUX__is_greater(b_is08, b_is08), "Must not be greater.");
  ok(!CRUX__is_greater(a_is16, a_is16), "Must not be greater.");
  ok(!CRUX__is_greater(a_is16, b_is16), "Must not be greater.");
  ok(CRUX__is_greater(b_is16, a_is16), "Must be greater.");
  ok(!CRUX__is_greater(b_is16, b_is16), "Must not be greater.");
  ok(!CRUX__is_greater(a_is32, a_is32), "Must not be greater.");
  ok(!CRUX__is_greater(a_is32, b_is32), "Must not be greater.");
  ok(CRUX__is_greater(b_is32, a_is32), "Must be greater.");
  ok(!CRUX__is_greater(b_is32, b_is32), "Must not be greater.");
  ok(!CRUX__is_greater(a_is64, a_is64), "Must not be greater.");
  ok(!CRUX__is_greater(a_is64, b_is64), "Must not be greater.");
  ok(CRUX__is_greater(b_is64, a_is64), "Must be greater.");
  ok(!CRUX__is_greater(b_is64, b_is64), "Must not be greater.");
}


void CRUX__compare_tests (void) {
  const Char a_char = CHAR_MIN;
  const Char b_char = CHAR_MAX;
  const Size a_size = SIZE_MIN;
  const Size b_size = SIZE_MAX;
  const IU08 a_iu08 = IU08_MIN;
  const IU08 b_iu08 = IU08_MAX;
  const IU16 a_iu16 = IU16_MIN;
  const IU16 b_iu16 = IU16_MAX;
  const IU32 a_iu32 = IU32_MIN;
  const IU32 b_iu32 = IU32_MAX;
  const IU64 a_iu64 = IU64_MIN;
  const IU64 b_iu64 = IU64_MAX;
  const IS08 a_is08 = IS08_MIN;
  const IS08 b_is08 = IS08_MAX;
  const IS16 a_is16 = IS16_MIN;
  const IS16 b_is16 = IS16_MAX;
  const IS32 a_is32 = IS32_MIN;
  const IS32 b_is32 = IS32_MAX;
  const IS64 a_is64 = IS64_MIN;
  const IS64 b_is64 = IS64_MAX;
  ok(CRUX__compare_char(a_char, a_char) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare_char(a_char, b_char) == CRUX__LESS, "Must be less.");
  ok(CRUX__compare_char(b_char, a_char) == CRUX__GREATER, "Must be greater.");
  ok(CRUX__compare_char(b_char, b_char) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare_size(a_size, a_size) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare_size(a_size, b_size) == CRUX__LESS, "Must be less.");
  ok(CRUX__compare_size(b_size, a_size) == CRUX__GREATER, "Must be greater.");
  ok(CRUX__compare_size(b_size, b_size) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_iu08, a_iu08) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_iu08, b_iu08) == CRUX__LESS, "Must be less.");
  ok(CRUX__compare(b_iu08, a_iu08) == CRUX__GREATER, "Must be greater.");
  ok(CRUX__compare(b_iu08, b_iu08) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_iu16, a_iu16) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_iu16, b_iu16) == CRUX__LESS, "Must be less.");
  ok(CRUX__compare(b_iu16, a_iu16) == CRUX__GREATER, "Must be greater.");
  ok(CRUX__compare(b_iu16, b_iu16) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_iu32, a_iu32) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_iu32, b_iu32) == CRUX__LESS, "Must be less.");
  ok(CRUX__compare(b_iu32, a_iu32) == CRUX__GREATER, "Must be greater.");
  ok(CRUX__compare(b_iu32, b_iu32) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_iu64, a_iu64) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_iu64, b_iu64) == CRUX__LESS, "Must be less.");
  ok(CRUX__compare(b_iu64, a_iu64) == CRUX__GREATER, "Must be greater.");
  ok(CRUX__compare(b_iu64, b_iu64) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_is08, a_is08) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_is08, b_is08) == CRUX__LESS, "Must be less.");
  ok(CRUX__compare(b_is08, a_is08) == CRUX__GREATER, "Must be greater.");
  ok(CRUX__compare(b_is08, b_is08) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_is16, a_is16) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_is16, b_is16) == CRUX__LESS, "Must be less.");
  ok(CRUX__compare(b_is16, a_is16) == CRUX__GREATER, "Must be greater.");
  ok(CRUX__compare(b_is16, b_is16) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_is32, a_is32) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_is32, b_is32) == CRUX__LESS, "Must be less.");
  ok(CRUX__compare(b_is32, a_is32) == CRUX__GREATER, "Must be greater.");
  ok(CRUX__compare(b_is32, b_is32) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_is64, a_is64) == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__compare(a_is64, b_is64) == CRUX__LESS, "Must be less.");
  ok(CRUX__compare(b_is64, a_is64) == CRUX__GREATER, "Must be greater.");
  ok(CRUX__compare(b_is64, b_is64) == CRUX__EQUAL, "Must be equal.");
}


void CRUX__compare_addr_tests (void) {
  const Char a_char = CHAR_MIN;
  const Char b_char = CHAR_MAX;
  const Size a_size = SIZE_MIN;
  const Size b_size = SIZE_MAX;
  const IU08 a_iu08 = IU08_MIN;
  const IU08 b_iu08 = IU08_MAX;
  const IU16 a_iu16 = IU16_MIN;
  const IU16 b_iu16 = IU16_MAX;
  const IU32 a_iu32 = IU32_MIN;
  const IU32 b_iu32 = IU32_MAX;
  const IU64 a_iu64 = IU64_MIN;
  const IU64 b_iu64 = IU64_MAX;
  const IS08 a_is08 = IS08_MIN;
  const IS08 b_is08 = IS08_MAX;
  const IS16 a_is16 = IS16_MIN;
  const IS16 b_is16 = IS16_MAX;
  const IS32 a_is32 = IS32_MIN;
  const IS32 b_is32 = IS32_MAX;
  const IS64 a_is64 = IS64_MIN;
  const IS64 b_is64 = IS64_MAX;
  CRUX__ResultOrder a_a_char = CRUX__compare_addr_char(&a_char, &a_char);
  CRUX__ResultOrder a_b_char = CRUX__compare_addr_char(&a_char, &b_char);
  CRUX__ResultOrder b_a_char = CRUX__compare_addr_char(&b_char, &a_char);
  CRUX__ResultOrder b_b_char = CRUX__compare_addr_char(&b_char, &b_char);
  CRUX__ResultOrder a_a_size = CRUX__compare_addr_size(&a_size, &a_size);
  CRUX__ResultOrder a_b_size = CRUX__compare_addr_size(&a_size, &b_size);
  CRUX__ResultOrder b_a_size = CRUX__compare_addr_size(&b_size, &a_size);
  CRUX__ResultOrder b_b_size = CRUX__compare_addr_size(&b_size, &b_size);
  CRUX__ResultOrder a_a_iu08 = CRUX__compare_addr_iu08(&a_iu08, &a_iu08);
  CRUX__ResultOrder a_b_iu08 = CRUX__compare_addr_iu08(&a_iu08, &b_iu08);
  CRUX__ResultOrder b_a_iu08 = CRUX__compare_addr_iu08(&b_iu08, &a_iu08);
  CRUX__ResultOrder b_b_iu08 = CRUX__compare_addr_iu08(&b_iu08, &b_iu08);
  CRUX__ResultOrder a_a_iu16 = CRUX__compare_addr_iu16(&a_iu16, &a_iu16);
  CRUX__ResultOrder a_b_iu16 = CRUX__compare_addr_iu16(&a_iu16, &b_iu16);
  CRUX__ResultOrder b_a_iu16 = CRUX__compare_addr_iu16(&b_iu16, &a_iu16);
  CRUX__ResultOrder b_b_iu16 = CRUX__compare_addr_iu16(&b_iu16, &b_iu16);
  CRUX__ResultOrder a_a_iu32 = CRUX__compare_addr_iu32(&a_iu32, &a_iu32);
  CRUX__ResultOrder a_b_iu32 = CRUX__compare_addr_iu32(&a_iu32, &b_iu32);
  CRUX__ResultOrder b_a_iu32 = CRUX__compare_addr_iu32(&b_iu32, &a_iu32);
  CRUX__ResultOrder b_b_iu32 = CRUX__compare_addr_iu32(&b_iu32, &b_iu32);
  CRUX__ResultOrder a_a_iu64 = CRUX__compare_addr_iu64(&a_iu64, &a_iu64);
  CRUX__ResultOrder a_b_iu64 = CRUX__compare_addr_iu64(&a_iu64, &b_iu64);
  CRUX__ResultOrder b_a_iu64 = CRUX__compare_addr_iu64(&b_iu64, &a_iu64);
  CRUX__ResultOrder b_b_iu64 = CRUX__compare_addr_iu64(&b_iu64, &b_iu64);
  CRUX__ResultOrder a_a_is08 = CRUX__compare_addr_is08(&a_is08, &a_is08);
  CRUX__ResultOrder a_b_is08 = CRUX__compare_addr_is08(&a_is08, &b_is08);
  CRUX__ResultOrder b_a_is08 = CRUX__compare_addr_is08(&b_is08, &a_is08);
  CRUX__ResultOrder b_b_is08 = CRUX__compare_addr_is08(&b_is08, &b_is08);
  CRUX__ResultOrder a_a_is16 = CRUX__compare_addr_is16(&a_is16, &a_is16);
  CRUX__ResultOrder a_b_is16 = CRUX__compare_addr_is16(&a_is16, &b_is16);
  CRUX__ResultOrder b_a_is16 = CRUX__compare_addr_is16(&b_is16, &a_is16);
  CRUX__ResultOrder b_b_is16 = CRUX__compare_addr_is16(&b_is16, &b_is16);
  CRUX__ResultOrder a_a_is32 = CRUX__compare_addr_is32(&a_is32, &a_is32);
  CRUX__ResultOrder a_b_is32 = CRUX__compare_addr_is32(&a_is32, &b_is32);
  CRUX__ResultOrder b_a_is32 = CRUX__compare_addr_is32(&b_is32, &a_is32);
  CRUX__ResultOrder b_b_is32 = CRUX__compare_addr_is32(&b_is32, &b_is32);
  CRUX__ResultOrder a_a_is64 = CRUX__compare_addr_is64(&a_is64, &a_is64);
  CRUX__ResultOrder a_b_is64 = CRUX__compare_addr_is64(&a_is64, &b_is64);
  CRUX__ResultOrder b_a_is64 = CRUX__compare_addr_is64(&b_is64, &a_is64);
  CRUX__ResultOrder b_b_is64 = CRUX__compare_addr_is64(&b_is64, &b_is64);
  ok(CRUX__trace_check(a_a_char.trace), "Must not have an error.");
  ok(a_a_char.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_b_char.trace), "Must not have an error.");
  ok(a_b_char.value == CRUX__LESS, "Must be less.");
  ok(CRUX__trace_check(b_a_char.trace), "Must not have an error.");
  ok(b_a_char.value == CRUX__GREATER, "Must be greater.");
  ok(CRUX__trace_check(b_b_char.trace), "Must not have an error.");
  ok(b_b_char.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_a_size.trace), "Must not have an error.");
  ok(a_a_size.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_b_size.trace), "Must not have an error.");
  ok(a_b_size.value == CRUX__LESS, "Must be less.");
  ok(CRUX__trace_check(b_a_size.trace), "Must not have an error.");
  ok(b_a_size.value == CRUX__GREATER, "Must be greater.");
  ok(CRUX__trace_check(b_b_size.trace), "Must not have an error.");
  ok(b_b_size.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_a_iu08.trace), "Must not have an error.");
  ok(a_a_iu08.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_b_iu08.trace), "Must not have an error.");
  ok(a_b_iu08.value == CRUX__LESS, "Must be less.");
  ok(CRUX__trace_check(b_a_iu08.trace), "Must not have an error.");
  ok(b_a_iu08.value == CRUX__GREATER, "Must be greater.");
  ok(CRUX__trace_check(b_b_iu08.trace), "Must not have an error.");
  ok(b_b_iu08.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_a_iu16.trace), "Must not have an error.");
  ok(a_a_iu16.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_b_iu16.trace), "Must not have an error.");
  ok(a_b_iu16.value == CRUX__LESS, "Must be less.");
  ok(CRUX__trace_check(b_a_iu16.trace), "Must not have an error.");
  ok(b_a_iu16.value == CRUX__GREATER, "Must be greater.");
  ok(CRUX__trace_check(b_b_iu16.trace), "Must not have an error.");
  ok(b_b_iu16.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_a_iu32.trace), "Must not have an error.");
  ok(a_a_iu32.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_b_iu32.trace), "Must not have an error.");
  ok(a_b_iu32.value == CRUX__LESS, "Must be less.");
  ok(CRUX__trace_check(b_a_iu32.trace), "Must not have an error.");
  ok(b_a_iu32.value == CRUX__GREATER, "Must be greater.");
  ok(CRUX__trace_check(b_b_iu32.trace), "Must not have an error.");
  ok(b_b_iu32.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_a_iu64.trace), "Must not have an error.");
  ok(a_a_iu64.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_b_iu64.trace), "Must not have an error.");
  ok(a_b_iu64.value == CRUX__LESS, "Must be less.");
  ok(CRUX__trace_check(b_a_iu64.trace), "Must not have an error.");
  ok(b_a_iu64.value == CRUX__GREATER, "Must be greater.");
  ok(CRUX__trace_check(b_b_iu64.trace), "Must not have an error.");
  ok(b_b_iu64.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_a_is08.trace), "Must not have an error.");
  ok(a_a_is08.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_b_is08.trace), "Must not have an error.");
  ok(a_b_is08.value == CRUX__LESS, "Must be less.");
  ok(CRUX__trace_check(b_a_is08.trace), "Must not have an error.");
  ok(b_a_is08.value == CRUX__GREATER, "Must be greater.");
  ok(CRUX__trace_check(b_b_is08.trace), "Must not have an error.");
  ok(b_b_is08.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_a_is16.trace), "Must not have an error.");
  ok(a_a_is16.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_b_is16.trace), "Must not have an error.");
  ok(a_b_is16.value == CRUX__LESS, "Must be less.");
  ok(CRUX__trace_check(b_a_is16.trace), "Must not have an error.");
  ok(b_a_is16.value == CRUX__GREATER, "Must be greater.");
  ok(CRUX__trace_check(b_b_is16.trace), "Must not have an error.");
  ok(b_b_is16.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_a_is32.trace), "Must not have an error.");
  ok(a_a_is32.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_b_is32.trace), "Must not have an error.");
  ok(a_b_is32.value == CRUX__LESS, "Must be less.");
  ok(CRUX__trace_check(b_a_is32.trace), "Must not have an error.");
  ok(b_a_is32.value == CRUX__GREATER, "Must be greater.");
  ok(CRUX__trace_check(b_b_is32.trace), "Must not have an error.");
  ok(b_b_is32.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_a_is64.trace), "Must not have an error.");
  ok(a_a_is64.value == CRUX__EQUAL, "Must be equal.");
  ok(CRUX__trace_check(a_b_is64.trace), "Must not have an error.");
  ok(a_b_is64.value == CRUX__LESS, "Must be less.");
  ok(CRUX__trace_check(b_a_is64.trace), "Must not have an error.");
  ok(b_a_is64.value == CRUX__GREATER, "Must be greater.");
  ok(CRUX__trace_check(b_b_is64.trace), "Must not have an error.");
  ok(b_b_is64.value == CRUX__EQUAL, "Must be equal.");
  CRUX__trace_clean(&a_a_char.trace);
  CRUX__trace_clean(&a_b_char.trace);
  CRUX__trace_clean(&b_a_char.trace);
  CRUX__trace_clean(&b_b_char.trace);
  CRUX__trace_clean(&a_a_size.trace);
  CRUX__trace_clean(&a_b_size.trace);
  CRUX__trace_clean(&b_a_size.trace);
  CRUX__trace_clean(&b_b_size.trace);
  CRUX__trace_clean(&a_a_iu08.trace);
  CRUX__trace_clean(&a_b_iu08.trace);
  CRUX__trace_clean(&b_a_iu08.trace);
  CRUX__trace_clean(&b_b_iu08.trace);
  CRUX__trace_clean(&a_a_iu16.trace);
  CRUX__trace_clean(&a_b_iu16.trace);
  CRUX__trace_clean(&b_a_iu16.trace);
  CRUX__trace_clean(&b_b_iu16.trace);
  CRUX__trace_clean(&a_a_iu32.trace);
  CRUX__trace_clean(&a_b_iu32.trace);
  CRUX__trace_clean(&b_a_iu32.trace);
  CRUX__trace_clean(&b_b_iu32.trace);
  CRUX__trace_clean(&a_a_iu64.trace);
  CRUX__trace_clean(&a_b_iu64.trace);
  CRUX__trace_clean(&b_a_iu64.trace);
  CRUX__trace_clean(&b_b_iu64.trace);
  CRUX__trace_clean(&a_a_is08.trace);
  CRUX__trace_clean(&a_b_is08.trace);
  CRUX__trace_clean(&b_a_is08.trace);
  CRUX__trace_clean(&b_b_is08.trace);
  CRUX__trace_clean(&a_a_is16.trace);
  CRUX__trace_clean(&a_b_is16.trace);
  CRUX__trace_clean(&b_a_is16.trace);
  CRUX__trace_clean(&b_b_is16.trace);
  CRUX__trace_clean(&a_a_is32.trace);
  CRUX__trace_clean(&a_b_is32.trace);
  CRUX__trace_clean(&b_a_is32.trace);
  CRUX__trace_clean(&b_b_is32.trace);
  CRUX__trace_clean(&a_a_is64.trace);
  CRUX__trace_clean(&a_b_is64.trace);
  CRUX__trace_clean(&b_a_is64.trace);
  CRUX__trace_clean(&b_b_is64.trace);
}




int main (int argc, char *argv[]) {
  plan(320);
  CRUX__is_less_tests();
  CRUX__is_less_equal_tests();
  CRUX__is_equal_tests();
  CRUX__is_greater_equal_tests();
  CRUX__is_greater_tests();
  CRUX__compare_tests();
  CRUX__compare_addr_tests();
  done_testing();
  return EXIT_SUCCESS;
}
